-- MySQL Script generated by MySQL Workbench
-- Wed Sep 22 17:21:59 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Announcement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Announcement` (
  `announcementID` INT NOT NULL AUTO_INCREMENT,
  `announcementMessage` TEXT NOT NULL,
  PRIMARY KEY (`announcementID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Complaint`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Complaint` (
  `complaintID` INT NOT NULL,
  `complaintMessage` TEXT NOT NULL,
  PRIMARY KEY (`complaintID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Contract`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Contract` (
  `ContractID` INT NOT NULL AUTO_INCREMENT,
  `EmployeeId` INT NOT NULL,
  `jobTitle` VARCHAR(45) NOT NULL,
  `floor` VARCHAR(45) NULL,
  `workingHours` INT NOT NULL,
  `salaryPerHour` INT NOT NULL,
  `startDate` DATE NOT NULL,
  `endDate` DATE NOT NULL,
  `reasenForTermination` TEXT NOT NULL,
  PRIMARY KEY (`ContractID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DeletedEmployee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DeletedEmployee` (
  `employeeID` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `phoneNumber` INT NULL,
  `email` VARCHAR(45) NULL,
  `adress` VARCHAR(45) NULL,
  `dateOfBirth` DATE NULL,
  `bsn` INT NOT NULL,
  `userName` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`employeeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Department` (
  `departmentID` INT NOT NULL AUTO_INCREMENT,
  `departmentName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`departmentID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `employeeID` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `phoneNumber` INT NULL,
  `email` VARCHAR(45) NULL,
  `adress` VARCHAR(45) NULL,
  `dateOfBirth` DATE NULL,
  `bsn` INT NOT NULL,
  `userName` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`employeeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Jobs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Jobs` (
  `jobID` INT NOT NULL AUTO_INCREMENT,
  `jobTitle` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`jobID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Product` (
  `productID` INT NOT NULL AUTO_INCREMENT,
  `barcode` VARCHAR(10) NOT NULL,
  `ProductName` VARCHAR(45) NOT NULL,
  `PorductType` VARCHAR(45) NOT NULL,
  `AmountInDepot` INT NOT NULL DEFAULT 0,
  `AmountInSales` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`productID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ProductTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ProductTypes` (
  `ProductTypeID` INT NOT NULL AUTO_INCREMENT,
  `ProductTypesName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ProductTypeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Scheduel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Scheduel` (
  `empID` INT NOT NULL,
  `scheduelDay` VARCHAR(45) NOT NULL,
  `time` VARCHAR(45) NOT NULL)
ENGINE = InnoDB;

ALTER TABLE `dbi461266`.`schedule` 
ADD COLUMN `ScheduleID` INT NOT NULL FIRST,
DROP PRIMARY KEY,
ADD PRIMARY KEY (`ScheduleID`);



-- -----------------------------------------------------
-- Table `mydb`.`Shifts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Shifts` (
  `day` VARCHAR(45) NOT NULL,
  `Morning` INT NOT NULL DEFAULT 1,
  `Afternoon` INT NOT NULL DEFAULT 1,
  `evening` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`day`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- add table `mydb`.`ShelfReplenishment`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `dbi461266`.`ShelfReplenishment` (
  `ShelfReplenishmentID` INT NOT NULL AUTO_INCREMENT,
  `ProductID` INT NOT NULL,
  `Amount` INT NOT NULL,
  PRIMARY KEY (`ShelfReplenishmentID`))
ENGINE = InnoDB;

ALTER TABLE `dbi461266`.`shelfreplenishment` 
ADD COLUMN `fufilled` TINYINT NOT NULL AFTER `Amount`;
-- -----------------------------------------------------
-- add table `mydb`.`Restock Requests`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `dbi461266`.`RestockReplenishment` (
  `RestockReplenishmentID` INT NOT NULL AUTO_INCREMENT,
  `ProductID` INT NOT NULL,
  `Amount` INT NOT NULL,
  PRIMARY KEY (`RestockReplenishmentID`))
ENGINE = InnoDB;

ALTER TABLE `dbi461266`.`restockreplenishment` 
ADD COLUMN `Fufilled` TINYINT NOT NULL AFTER `Amount`;

CREATE TABLE IF NOT EXISTS `dbi461266`.`WorkPrefrance` (
  `PrefranceID` INT NOT NULL AUTO_INCREMENT,
  `EmployeeID` INT NOT NULL,
  `Prefered` TINYINT NOT NULL,
  `Day` VARCHAR(45) NULL,
  `Time` VARCHAR(45) NULL,
  PRIMARY KEY (`PrefranceID`))
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `dbi461266`.`atendance` (
  `CheckDate` DATE NOT NULL,
  `EmployeeID` INT NOT NULL,
  `CheckInTime` TIME NULL,
  `CheckOutTime` TIME NULL,
  PRIMARY KEY (`CheckDate`),
ENGINE = InnoDB;



START TRANSACTION;
USE `dbi461266`;
INSERT INTO `dbi461266`.`WorkPrefrance` (`PrefranceID`, `EmployeeID`, `Prefered`, `Day`, `Time`) VALUES (1, 1, 1, 'Mondag', 'Morning');

COMMIT;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`Announcement`
-- -----------------------------------------------------
START TRANSACTION;
USE `dbi461266`;
INSERT INTO `dbi461266`.`Announcement` (`announcementID`, `announcementMessage`) VALUES (1, 'hello');
INSERT INTO `dbi461266`.`Announcement` (`announcementID`, `announcementMessage`) VALUES (2, 'first');
INSERT INTO `dbi461266`.`Announcement` (`announcementID`, `announcementMessage`) VALUES (3, 'Error');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Complaint`
-- -----------------------------------------------------
START TRANSACTION;
USE `dbi461266`;
INSERT INTO `dbi461266`.`Complaint` (`complaintID`, `complaintMessage`) VALUES (1, 'Error');
INSERT INTO `dbi461266`.`Complaint` (`complaintID`, `complaintMessage`) VALUES (2, 'hello');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Contract`
-- -----------------------------------------------------
START TRANSACTION;
USE `dbi461266`;
INSERT INTO `dbi461266`.`Contract` (`ContractID`, `EmployeeId`, `jodtitle`,  `WorkHoursPerWeek`, `salaryPerHour`, `startDate`, `endDate`, `ReasonForTermination`) VALUES (1, 1, 'OWNER',  40, 100, '2020-12-12', '2020-12-12', 'NONE');
INSERT INTO `dbi461266`.`Contract` (`ContractID`, `EmployeeId`, `jodtitle`, `WorkHoursPerWeek`, `salaryPerHour`, `startDate`, `endDate`, `ReasonForTermination`) VALUES (2, 1, 'SALES EMPLOYEE',  40, 100, '2020-12-12', '2020-12-12', 'NONE');
INSERT INTO `dbi461266`.`Contract` (`ContractID`, `EmployeeId`, `jodtitle`,  `WorkHoursPerWeek`, `salaryPerHour`, `startDate`, `endDate`, `ReasonForTermination`) VALUES (3, 1, 'SALES EMPLOYEE',  40, 100, '2020-12-12', '2020-12-12', 'NONE');
INSERT INTO `dbi461266`.`Contract` (`ContractID`, `EmployeeId`, `jodtitle`, `WorkHoursPerWeek`, `salaryPerHour`, `startDate`, `endDate`, `ReasonForTermination`) VALUES (4, 1, 'SALES EMPLOYEE',  40, 100, '2020-12-12', '2020-12-12', 'NONE');
INSERT INTO `dbi461266`.`Contract` (`ContractID`, `EmployeeId`, `jodtitle`,  `WorkHoursPerWeek`, `salaryPerHour`, `startDate`, `endDate`, `ReasonForTermination`) VALUES (5, 1, 'SALES EMPLOYEE', 40, 100, '2020-12-12', '2020-12-12', 'NONE');
INSERT INTO `dbi461266`.`Contract` (`ContractID`, `EmployeeId`, `jodtitle`, `WorkHoursPerWeek`, `salaryPerHour`, `startDate`, `endDate`, `ReasonForTermination`) VALUES (6, 1, 'SALES EMPLOYEE', 40, 100, '2020-12-12', '2020-12-12', 'NONE');
INSERT INTO `dbi461266`.`Contract` (`ContractID`, `EmployeeId`, `jodtitle`, `WorkHoursPerWeek`, `salaryPerHour`, `startDate`, `endDate`, `ReasonForTermination`) VALUES (7, 1, 'SALES EMPLOYEE',  40, 100, '2020-12-12', '2020-12-12', 'NONE');
INSERT INTO `dbi461266`.`Contract` (`ContractID`, `EmployeeId`, `jodtitle`,  `WorkHoursPerWeek`, `salaryPerHour`, `startDate`, `endDate`, `ReasonForTermination`) VALUES (8, 1, 'SALES EMPLOYEE',  40, 100, '2020-12-12', '2020-12-12', 'NONE');
INSERT INTO `dbi461266`.`Contract` (`ContractID`, `EmployeeId`, `jodtitle`,  `WorkHoursPerWeek`, `salaryPerHour`, `startDate`, `endDate`, `ReasonForTermination`) VALUES (9, 1, 'SALES EMPLOYEE',  40, 100, '2020-12-12', '2020-12-12', 'NONE');
INSERT INTO `dbi461266`.`Contract` (`ContractID`, `EmployeeId`, `jodtitle`, `WorkHoursPerWeek`, `salaryPerHour`, `startDate`, `endDate`, `ReasonForTermination`) VALUES (10, 1, 'SALES EMPLOYEE',  40, 100, '2020-12-12', '2020-12-12', 'NONE');
COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`DeletedEmployee`
-- -----------------------------------------------------
START TRANSACTION;
USE `dbi461266`;
INSERT INTO `dbi461266`.`DeletedEmployee` (`employeeID`, `firstName`, `lastName`, `phoneNumber`, `email`, `adress`, `dateOfBirth`, `bsn`, `userName`, `password`) VALUES (2, 'I\'ll', 'Be back', NULL, NULL, NULL, NULL, 123, 'i', '1');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Department`
-- -----------------------------------------------------
START TRANSACTION;
USE `dbi461266`;
INSERT INTO `dbi461266`.`Department` (`departmentID`, `departmentName`) VALUES (1, 'Sales');
INSERT INTO `dbi461266`.`Department` (`departmentID`, `departmentName`) VALUES (2, 'Office');
INSERT INTO `dbi461266`.`Department` (`departmentID`, `departmentName`) VALUES (3, 'Depot');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Employee`
-- -----------------------------------------------------
START TRANSACTION;
USE `dbi461266`;
INSERT INTO `dbi461266`.`Employee` (`employeeID`, `firstName`, `lastName`, `phoneNumber`, `email`, `adress`, `dateOfBirth`, `bsn`, `userName`, `password`) VALUES (1, 'Lars', 'Kluijtmans', 0000, 'lars@gmail.com', NULL, NULL, 1234, 'Lars', '1');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Jobs`
-- -----------------------------------------------------
START TRANSACTION;
USE `dbi461266`;
INSERT INTO `dbi461266`.`Jobs` (`jobID`, `jobTitle`) VALUES (1, 'Owner');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Product`
-- -----------------------------------------------------
START TRANSACTION;
USE `dbi461266`;
INSERT INTO `dbi461266`.`Product` (`productID`, `barcode`, `ProductName`, `PorductType`, `AmountInDepot`, `AmountInSales`) VALUES (1, 'k1', 'Knife', 'Kitchen and Home', 100, 12);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`ProductTypes`
-- -----------------------------------------------------
START TRANSACTION;
USE `dbi461266`;
INSERT INTO `dbi461266`.`ProductTypes` (`ProductTypeID`, `ProductTypesName`) VALUES (1, 'Kitchen and Home');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Scheduel`
-- -----------------------------------------------------
START TRANSACTION;
USE `dbi461266`;
INSERT INTO `dbi461266`.`Scheduel` (`empID`, `scheduelDay`, `time`) VALUES (1, 'wednesday', 'morning');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Shifts`
-- -----------------------------------------------------
START TRANSACTION;
USE `dbi461266`;
INSERT INTO `dbi461266`.`Shifts` (`day`, `Morning`, `Afternoon`, `evening`) VALUES ('monday', 1, 1, 1);
INSERT INTO `dbi461266`.`Shifts` (`day`, `Morning`, `Afternoon`, `evening`) VALUES ('tuseday', 1, 1, 1);
INSERT INTO `dbi461266`.`Shifts` (`day`, `Morning`, `Afternoon`, `evening`) VALUES ('wednsday', 1, 1, 1);
INSERT INTO `dbi461266`.`Shifts` (`day`, `Morning`, `Afternoon`, `evening`) VALUES ('thursday', 1, 1, 1);
INSERT INTO `dbi461266`.`Shifts` (`day`, `Morning`, `Afternoon`, `evening`) VALUES ('friday', 1, 1, 1);
INSERT INTO `dbi461266`.`Shifts` (`day`, `Morning`, `Afternoon`, `evening`) VALUES ('stareday', 1, 1, 1);
INSERT INTO `dbi461266`.`Shifts` (`day`, `Morning`, `Afternoon`, `evening`) VALUES ('sunday', 1, 1, 1);



INSERT INTO `dbi461266`.`schedule` (`ScheduleID`, `Department`, `Day`) VALUES ('1', 'Sales', 'Monday');
INSERT INTO `dbi461266`.`schedule` (`ScheduleID`, `Department`, `Day`) VALUES ('2', 'Sales', 'Tusday');
INSERT INTO `dbi461266`.`schedule` (`ScheduleID`, `Department`, `Day`) VALUES ('3', 'Sales', 'Wednesday');
INSERT INTO `dbi461266`.`schedule` (`ScheduleID`, `Department`, `Day`) VALUES ('4', 'Sales', 'Thursday');
INSERT INTO `dbi461266`.`schedule` (`ScheduleID`, `Department`, `Day`) VALUES ('5', 'Sales', 'Friday');
INSERT INTO `dbi461266`.`schedule` (`ScheduleID`, `Department`, `Day`) VALUES ('6', 'Sales', 'Saterday');
INSERT INTO `dbi461266`.`schedule` (`ScheduleID`, `Department`, `Day`) VALUES ('7', 'Sales', 'Sunday');
INSERT INTO `dbi461266`.`schedule` (`ScheduleID`, `Department`, `Day`) VALUES ('8', 'Depot', 'Monday');
INSERT INTO `dbi461266`.`schedule` (`ScheduleID`, `Department`, `Day`) VALUES ('9', 'Depot', 'Tusday');
INSERT INTO `dbi461266`.`schedule` (`ScheduleID`, `Department`, `Day`) VALUES ('10', 'Depot', 'Wednesday');
INSERT INTO `dbi461266`.`schedule` (`ScheduleID`, `Department`, `Day`) VALUES ('11', 'Depot', 'Thursday');
INSERT INTO `dbi461266`.`schedule` (`ScheduleID`, `Department`, `Day`) VALUES ('12', 'Depot', 'Friday');
INSERT INTO `dbi461266`.`schedule` (`ScheduleID`, `Department`, `Day`) VALUES ('13', 'Depot', 'Saterday');
INSERT INTO `dbi461266`.`schedule` (`ScheduleID`, `Department`, `Day`) VALUES ('14', 'Depot', 'Sunday');
INSERT INTO `dbi461266`.`schedule` (`ScheduleID`, `Department`, `Day`) VALUES ('15', 'Office', 'Monday');
INSERT INTO `dbi461266`.`schedule` (`ScheduleID`, `Department`, `Day`) VALUES ('16', 'Office', 'Tusday');
INSERT INTO `dbi461266`.`schedule` (`ScheduleID`, `Department`, `Day`) VALUES ('17', 'Office', 'Wednesday');
INSERT INTO `dbi461266`.`schedule` (`ScheduleID`, `Department`, `Day`) VALUES ('18', 'Office', 'Thursday');
INSERT INTO `dbi461266`.`schedule` (`ScheduleID`, `Department`, `Day`) VALUES ('19', 'Office', 'Friday');
INSERT INTO `dbi461266`.`schedule` (`ScheduleID`, `Department`, `Day`) VALUES ('20', 'Office', 'Saterday');
INSERT INTO `dbi461266`.`schedule` (`ScheduleID`, `Department`, `Day`) VALUES ('21', 'Office', 'Sunday');

COMMIT;


ALTER TABLE `dbi461266`.`shelfreplenishment` 
ADD INDEX `ProductID_idx` (`ProductID` ASC):
;
ALTER TABLE `dbi461266`.`shelfreplenishment` 
ADD CONSTRAINT `ProductID`
  FOREIGN KEY (`ProductID`)
  REFERENCES `dbi461266`.`product` (`ProductID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `dbi461266`.`restockreplenishment` 
ADD CONSTRAINT `ProductID2`
  FOREIGN KEY (`ProductID`)
  REFERENCES `dbi461266`.`product` (`ProductID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
